### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (128,127) (0,127) 

### ISSUE THREAD

**Issue by dayu-chen** [huankoh/CST-GL#2]
Hi, I used the WADI_14days data set when reproducing this code. According to the running instructions you gave, I got the following error after running the run.py file:
```
Traceback (most recent call last):
  File "run.py", line 315, in <module>
    pointwise, early = main(i)
  File "run.py", line 297, in main
    indicator, prediction = anomaly_detector.scorer(args.pca_compo)
  File "/mnt/anomaly_dd.py", line 48, in scorer
    test_norm = error_sw_normalizer(full_abs,self.window_length,self.batch_size,len(self.test_obs))
  File "/mnt/anomaly_dd.py", line 102, in error_sw_normalizer
    batch_norm_error = (batch_error_mat - median) / iqr
ValueError: operands could not be broadcast together with shapes (128,127) (0,127) 
```
I don't know what's going on, and I sincerely hope you can give effective guidance, thank you!

**Comment by huankoh** [comment]
I never experienced this error, please let me know if you have resolved this issue and I can make adjustment to the current repo.
